### PR TITLE
Add f64 functionality

### PR DESCRIPTION
**Pull request by TheHellBox**
Most of the functions are untested, but there is no reasons for them not to work.

### CODE REVIEW

**Comment by jackmott** [comment]
you can use the little program in example folder to test pretty easy if you like.

**Comment by TheHellBox** [comment]
I've tested fbm on scalar and avx2.
Cellular is untested, as well as sse2/sse41, but I might test those tomorrow if you wish

**Comment by jackmott** [comment]
i can check stuff out later tonight

**Comment by TheHellBox** [comment]
Actually... I've found that noise on avx2 has quite a lot of artifacts on bigger scale, and sse2 seem to not work at all... Meh.
But scalar works just fine

**Pull request merged**
